import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('public/images',{recursive:true});
const covers=[
 {slug:'nextify',name:'Nextify',subtitle:'A better way to migrate.',bg:'#e4eae6',ink:'#485c50',labels:['React','Transform','Validate','Next.js'],tag:'MIGRATE. VERIFY. IMPROVE.'},
 {slug:'ai-org-simulation',name:'AI Org',subtitle:'From a brief to a team.',bg:'#e5e8f0',ink:'#505c78',labels:['PRD','Analyze','Simulate','Report'],tag:'SIMULATING COLLABORATION'},
 {slug:'alarm-u',name:'AlarmU',subtitle:'Care beyond the feature.',bg:'#eee8de',ink:'#806b4d',labels:['Admin','API','Protect','Deliver'],tag:'MAINTAIN. PROTECT. OPERATE.'},
 {slug:'replendar',name:'Replendar',subtitle:'Connecting the workflow.',bg:'#ece5eb',ink:'#7b6378',labels:['Design','React','API','Connect'],tag:'BUILDING TOGETHER'}
];
for(const c of covers){
 const cards=c.labels.map((label,i)=>{const x=110+(i%2)*320,y=352+Math.floor(i/2)*110;return `<rect x="${x}" y="${y}" width="260" height="74" rx="8" fill="white" fill-opacity=".48" stroke="${c.ink}" stroke-opacity=".18"/><text x="${x+21}" y="${y+27}" font-family="Arial,sans-serif" font-size="11" fill="${c.ink}" opacity=".65">0${i+1}</text><text x="${x+21}" y="${y+52}" font-family="Arial,sans-serif" font-size="20" fill="${c.ink}">${label}</text>`;}).join('');
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="700" viewBox="0 0 800 700"><rect width="800" height="700" fill="${c.bg}"/><path d="M110 300h580M110 580h580" stroke="${c.ink}" stroke-opacity=".18"/><text x="110" y="154" font-family="Arial,sans-serif" font-size="12" letter-spacing="2" fill="${c.ink}" opacity=".7">${c.tag}</text><text x="105" y="225" font-family="Arial,sans-serif" font-size="67" letter-spacing="-3" font-weight="600" fill="${c.ink}">${c.name}</text><text x="110" y="264" font-family="Arial,sans-serif" font-size="19" fill="${c.ink}" opacity=".8">${c.subtitle}</text>${cards}<path d="M380 390h39m-8-6 8 6-8 6M380 500h39m-8-6 8 6-8 6" fill="none" stroke="${c.ink}" stroke-opacity=".6"/><text x="110" y="622" font-family="Arial,sans-serif" font-size="11" letter-spacing="2" fill="${c.ink}" opacity=".65">COLDGEON / SELECTED WORK</text></svg>`;
 await writeFile(`public/images/${c.slug}.svg`,svg);
 const wideCards=c.labels.map((label,i)=>{const x=62+i*245;return `<rect x="${x}" y="292" width="224" height="98" rx="8" fill="white" fill-opacity=".48" stroke="${c.ink}" stroke-opacity=".18"/><text x="${x+20}" y="324" font-family="Arial,sans-serif" font-size="12" fill="${c.ink}">0${i+1}</text><text x="${x+20}" y="364" font-family="Arial,sans-serif" font-size="23" fill="${c.ink}">${label}</text>`;}).join('');
 const wide=`<svg xmlns="http://www.w3.org/2000/svg" width="1100" height="550" viewBox="0 0 1100 550"><rect width="1100" height="550" fill="${c.bg}"/><text x="62" y="86" font-family="Arial,sans-serif" font-size="13" letter-spacing="2" fill="${c.ink}">${c.tag}</text><text x="58" y="180" font-family="Arial,sans-serif" font-size="80" letter-spacing="-3" font-weight="600" fill="${c.ink}">${c.name}</text><text x="62" y="224" font-family="Arial,sans-serif" font-size="22" fill="${c.ink}">${c.subtitle}</text>${wideCards}<path d="M62 435h960" stroke="${c.ink}" stroke-opacity=".2"/><text x="62" y="487" font-family="Arial,sans-serif" font-size="13" letter-spacing="2" fill="${c.ink}">COLDGEON / SELECTED WORK</text></svg>`;
 await writeFile(`public/images/${c.slug}-wide.svg`,wide);
}
